    <nav id="ueber_header">
      <ul>
        <li>
          Anleitung
        </li>
        <li>
          Theoretisch
        </li>
        <li>
          Technisch
        </li>
        <li>
          Links
        </li>
        <li>
          Persönliches
        </li>
      </ul>
    </nav>